// Generated by Outstatic - do not edit manually

import type { Posts, PostsFields } from './posts'
import type { Projects, ProjectsFields } from './projects'

export type CollectionName = 'posts' | 'projects'

export type SingletonName = never

export interface Collections {
  'posts': Posts
  'projects': Projects
}

export interface Singletons {
}

export type CollectionDocument<C extends CollectionName> = Collections[C]
export type SingletonDocument<S extends SingletonName> = Singletons[S]

/** Union of all document field types for use with load() */
export type AllDocuments = PostsFields | ProjectsFields
