// Generated by Outstatic - do not edit manually
import type { OstDocument } from 'outstatic'

export interface PostsFields {
  coverImage?: string
  description?: string
}

export interface Posts extends OstDocument<PostsFields> {}

export type PostsField = keyof Posts
