// Generated by Outstatic - do not edit manually
import type { OstDocument } from 'outstatic'

export interface ProjectsFields {
  coverImage?: string
}

export interface Projects extends OstDocument<ProjectsFields> {}

export type ProjectsField = keyof Projects
