// Generated by Outstatic - do not edit manually
import type { OstDocument } from 'outstatic'

export interface ProjectsFields {}

export interface Projects extends OstDocument<ProjectsFields> {}

export type ProjectsField = keyof Projects
